/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_MLManager */

#ifndef _Included_server_MLManager
#define _Included_server_MLManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server_MLManager
 * Method:    train
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_server_MLManager_train
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
